development:
  ignored_user_names: <%= ENV["IGNORED_USER_NAMES"] || "[slackbot, testbot]" %>
  secret_key_base: 72cb95f371744a945d8a82696b5e9cb786128eb3d26d44c998966f935a8795c1af4ab9bc0edfe5608c750a917bd4909ea52b92a5c70482dde87fff6a6c85b169
  slack_subdomain: <%= ENV["SLACK_SUBDOMAIN"] || "bucket" %>
  slack_startup_token: <%= ENV["SLACK_STARTUP_TOKEN"] || "SLACK_STARTUP_TOKEN" %>
  slack_triggers_token: <%= ENV["SLACK_TRIGGERS_TOKEN"] || "SLACK_TRIGGERS_TOKEN" %>

test:
  ignored_user_names: <%= ENV["IGNORED_USER_NAMES"] || "[slackbot, testbot]" %>
  secret_key_base: 2721964b1ae6f38738373830a169c3e12ffa68f8fb04d4b8d8b5be9f11169877b46501ee06b5b72bf1f352c74399620612d26ab9d9babcde1c48dd63a1aa0ac7
  slack_subdomain: <%= ENV["SLACK_SUBDOMAIN"] || "bucket" %>
  slack_triggers_token: <%= ENV["SLACK_TRIGGERS_TOKEN"] || "SLACK_TRIGGERS_TOKEN" %>
  slack_startup_token: <%= ENV["SLACK_STARTUP_TOKEN"] || "SLACK_STARTUP_TOKEN" %>

production:
  ignored_user_names: <%= ENV["IGNORED_USER_NAMES"] || "slackbot" %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slack_subdomain: <%= ENV["SLACK_SUBDOMAIN"] %>
  slack_triggers_token: <%= ENV["SLACK_TRIGGERS_TOKEN"] %>
  slack_startup_token: <%= ENV["SLACK_STARTUP_TOKEN"] %>
